var express = require('express');
var http = require('http');
var gzippo = require('gzippo');
var morgan = require('morgan');
var bodyParser = require('body-parser');
var methodOverride = require('method-override');
var app = express();
app.use(morgan('dev'));
app.use(bodyParser());
app.use(methodOverride());
app.use(gzippo.staticGzip('' + __dirname));
var server = http.createServer(app);
server.listen(process.env.PORT || 5000);